### ISSUE TITLE
Add authorization, validations, more

### ISSUE THREAD

**Issue by canweriotnow** [johm/freeskool#1]
Pull requests aren't yet enabled. 

So just wanted to address some of the missing model logic, tests, etc. 

Visible here: https://github.com/canweriotnow/freeskool/commit/f8a89e8f79aa545fd3a986ae269897d3f0888d39

Next step is calendar, I think.

**Comment by johm** [comment]
how do i enable pull requests?

**Comment by canweriotnow** [comment]
Never mind, I was being stupid. I have to do it from my fork.
